### ISSUE TITLE
Airship build is not available in Firefox

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/airship#430] opened 2018-10-23 11:04 UTC
### Context

When opening Airship in Firefox, it says it is not available for this browser.

### Steps to Reproduce

1. Open Airship reference documentation in Firefox https://carto.com/developers/airship/reference/

### Current Result

<img width="844" alt="screen shot 2018-10-23 at 13 02 58" src="https://user-images.githubusercontent.com/3824953/47356358-1dff3a00-d6c4-11e8-81bc-6317e633d0d1.png">

### Expected result

It should be available in Firefox. 

### Browser and version

Firefox

### Additional info

It would be great to have the list of browsers & versions where Airship is supported.

**Comment by ivanmalagon** [comment] 2018-10-23 14:35
Fixed in `beta.4`.

**Comment by AbelVM** [comment] 2018-11-13 16:08
Looks like there's a regression on this in `beta.6` :(

**Comment by AbelVM** [comment] 2018-11-15 11:14
![image](https://user-images.githubusercontent.com/9017165/48549378-eef97400-e8cf-11e8-8c8f-cec89e593f1a.png)

**Comment by IagoLast** [comment] 2018-11-15 12:31
@AbelVM we are already on beta.10 does this still happens?

**Comment by AbelVM** [comment] 2018-11-16 06:59
Looks like fixed in beta.10. I'm having other issues with Firefox, but I need to triage them to blame Airship or not.

**Comment by IagoLast** [comment] 2018-11-16 09:09
> Looks like fixed in beta.10

**Closed** 2018-11-16 09:10 UTC
Labels: BUG :bug:
